version: '3.7'
services:
  frontend:
    build:
      context: frontend/docker/development/nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
  nginx:
    build:
      context: api/docker/development/nginx
    ports:
      - "8081:80"
    volumes:
      - ./api:/app
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: api/docker/development/php-fpm
    volumes:
      - ./api:/app